"""Criar tabela Diario

Revision ID: 08287b1cc367
Revises: 
Create Date: 2025-08-06 02:25:02.861117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08287b1cc367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('disciplina', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diario')
    # ### end Alembic commands ###
